### PR TITLE
flaml 1.2.4 :snowflake:

### PR DESCRIPTION
**Pull request by Andrii-Osipov**
flaml 1.2.4 :snowflake:

**Destination channel:** Snowflake

- [PKG-6176](https://anaconda.atlassian.net/browse/PKG-6176) 
- [source code](https://github.com/microsoft/FLAML/tree/v1.2.4)
- [PyPi](https://pypi.org/project/FLAML/)
- [conda-forge](https://github.com/conda-forge/flaml-feedstock)

[PKG-6176]: https://anaconda.atlassian.net/browse/PKG-6176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: recipe/meta.yaml [hunk 1]
```diff
@@ -1,52 +1,76 @@
...
-    - python >=3.6
+    - python
+    - wheel
+    - setuptools
   run:
-    - numpy >=1.17.0rc1
+    - python
+    # AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.
+    # Set last compatible version for NumPy
+    - numpy >=1.17.0rc1,<=2.0
```
Comment (ifitchet) [inline recipe/meta.yaml]: Should this be `<2.0` then?

Comment (skupr-anaconda) [inline recipe/meta.yaml]:
```suggestion
    - numpy >=1.17.0,<=2.0
```
Because we are not building release candidates, alpha, and beta versions of packages

Comment (Andrii-Osipov) [reply recipe/meta.yaml:30]: @ifitchet API is compatible if I am using a version less then 2.0. And this error has disappeared.

Comment (Andrii-Osipov) [reply recipe/meta.yaml]: yeap

File: recipe/meta.yaml [hunk 2]
```diff
@@ -1,52 +1,76 @@
...
     - scipy >=1.4.1
-    - pandas >=1.1.4
     - scikit-learn >=0.24
-    - python >=3.6
+    # return klass(values, ndim=ndim, placement=placement, refs=refs)
+    # TypeError: Argument 'placement' has incorrect type (expected pandas._libs.internals.BlockPlacement, got numpy.ndarray)
+    # Set last compatible versions for xgboost and pandas <2.0
+    - pandas >=1.1.4,<2.0
+    - xgboost >=0.90,<2.0
+
```
Comment (skupr-anaconda) [inline recipe/meta.yaml:87]: Could you add `run_constrained` with these optional dependencies:
```
run_constrained:
  # Autogen
  - openai ==0.27.4
  # Blendsearch
  - optuna ==2.8.0
  # Catboost
  - catboost >=0.26
  # Forecast
  - holidays <0.14
  - prophet >=1.0.1
  - statsmodels >=0.12.2
  - hcrystalball ==0.1.10
  - pytorch-forecasting >=0.9.0
  # Hf
  - transformers ==4.26
  # Nlp
  - transformers ==4.26
  # Notebook
  - openml ==0.10.2
  # Openai
  - openai ==0.27.4
  # Ray
  - ray >=1.13,<2.dev0
  # Spark
  - pyspark >=3.2.0
  - joblibspark >=0.5.0
  # Synapse 
  - joblibspark >=0.5.0
  - optuna ==2.8.0
  - pyspark >=3.2.0
  # Ts_forecast
  - holidays <0.14
  - prophet >=1.0.1
  - statsmodels >=0.12.2
  - hcrystalball ==0.1.10
  # Vw 
  - vowpalwabbit >=8.10.0,<9.0.0
```

I generated it by `grayskull pypi https://github.com/microsoft/FLAML --tag v1.2.4 --extras-require-all` and removed the test dependencies

File: recipe/meta.yaml (hunk 1 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml]: done!
the patch is created.

File: recipe/meta.yaml (hunk 2 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml:87]: @skupr-anaconda all these dependencies are for the tests.

Comment (ifitchet) [reply recipe/meta.yaml:87]: @skupr-anaconda Interesting, I've always used `grayskull pypi {name}={version}` whereas, I guess, your variant allows you to use arbitrary repos...

Comment (skupr-anaconda) [reply recipe/meta.yaml:87]: Not only the tests. It's for extending functionality, see the full list https://microsoft.github.io/FLAML/docs/Installation/

Comment (skupr-anaconda) [reply recipe/meta.yaml:87]: The test environment fails:
`WARNING: failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {'package flaml-1.2.4-py311h06a4308_0 has constraint openml 0.10.2 conflicting with openml-0.12.2-pyhd3eb1b0_0'}`

It's because you set `openml ==0.12.2` in `test/requires`. If it works with 0.12.2 so you can modify run_constrained

Comment (Andrii-Osipov) [reply recipe/meta.yaml:87]: done

**Review by skupr-anaconda — APPROVED** [review]

File: recipe/meta.yaml [hunk 3]
```diff
@@ -1,52 +1,120 @@
...
+    # return klass(values, ndim=ndim, placement=placement, refs=refs)
+    # TypeError: Argument 'placement' has incorrect type (expected pandas._libs.internals.BlockPlacement, got numpy.ndarray)
+    # Set last compatible versions for xgboost and pandas <2.0
+    - pandas >=1.1.4,<2.0
+    - xgboost >=0.90,<2.0
+  run_constrained:
+    # Autogen
+    - openai ==0.27.4
+    # Blendsearch
+    - optuna ==2.8.0
```
Comment (ifitchet) [inline recipe/meta.yaml]: We don't have `optuna ==2.8.0`.

File: recipe/meta.yaml [hunk 4]
```diff
@@ -1,52 +1,120 @@
...
+    # Catboost
+    - catboost >=0.26
+    # Forecast
+    - holidays <0.14
+    - prophet >=1.0.1
+    - statsmodels >=0.12.2
+    - hcrystalball ==0.1.10
```
Comment (ifitchet) [inline recipe/meta.yaml]: We don't have `hcrystalball`.

File: recipe/meta.yaml [hunk 5]
```diff
@@ -1,52 +1,120 @@
...
+    - pytorch-forecasting >=0.9.0
+    # Hf
+    - transformers ==4.26
```
Comment (ifitchet) [inline recipe/meta.yaml]: We don't have `transformers ==4.26`.

File: recipe/meta.yaml [hunk 6]
```diff
@@ -1,52 +1,120 @@
...
+    # Nlp
+    - transformers ==4.26
+    # Notebook
+    # Duplicated in the test section, comment this line to avoid compilation error.
+    #- openml ==0.10.2,<0.13
+    # Openai
+    - openai ==0.27.4
+    # Ray
+    - ray >=1.13,<2.dev0
```
Comment (ifitchet) [inline recipe/meta.yaml:71]: This should (probably) be `ray-tune` and we don't have a version `<2`.

File: recipe/meta.yaml [hunk 7]
```diff
@@ -1,52 +1,120 @@
...
+    # Spark
+    - pyspark >=3.2.0
+    - joblibspark >=0.5.0
```
Comment (ifitchet) [inline recipe/meta.yaml:74]: We don't have a `joblibspark`

File: recipe/meta.yaml (hunk 3 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: `optuna ==2.8.0` is an optional dependency with a constraint. We make sure that the end user won't install an incompatible version if it tries to do it from another channel, say, conda-forge.

File: recipe/meta.yaml (hunk 4 above)
Comment (skupr-anaconda) [reply recipe/meta.yaml]: Yes, and if we'll build `hcrystalball` tomorrow we are confident that `hcrystalball ==0.1.10` will work in a user environment but not other versions

Comment (skupr-anaconda) [reply recipe/meta.yaml]: It's identical to this https://github.com/AnacondaRecipes/pandas-feedstock/blob/master/recipe/meta.yaml#L47-L100

File: recipe/meta.yaml (hunk 6 above)
Comment (ifitchet) [reply recipe/meta.yaml:71]: How was this resolved?

File: recipe/meta.yaml (hunk 3 above)
Comment (ifitchet) [reply recipe/meta.yaml]: OK, that's fair.

File: recipe/meta.yaml (hunk 4 above)
Comment (ifitchet) [reply recipe/meta.yaml]: OK.

File: recipe/meta.yaml (hunk 6 above)
Comment (ifitchet) [reply recipe/meta.yaml:71]: I read [this as requiring](https://github.com/microsoft/FLAML/blob/v1.2.4/setup.py#L83-L85) `ray-tune`, for a start:

File: recipe/meta.yaml [hunk 8]
```diff
@@ -1,52 +1,120 @@
...
+    - catboost >=0.26
+    # Forecast
+    - holidays <0.14
+    - prophet >=1.0.1
+    - statsmodels >=0.12.2
+    - hcrystalball >=0.1.10,<0.2
+    - pytorch-forecasting >=0.9.0
+    # Hf
+    - transformers >=4.26,<5
+    # Nlp
```
Comment (boldorider4) [inline recipe/meta.yaml:59]: duplicated requirement?

File: recipe/meta.yaml [hunk 9]
```diff
@@ -1,52 +1,120 @@
...
-    - scikit-learn >=0.24
-  source_files:
-    # list all conda related test files here
-    # note: keep the conda related tests directly in the test folder, so that bundling to tar.gz includes them
-    # or just extend the test_conda_distribution.py file with more tests (and make sure to mark it as conda)
-    - test/test_conda_distribution.py
-  commands:
-    - pytest -m conda
+    # In the snowflake channel avaliable only openml==0.12.2 (default is 0.10.2)
+    - openml ==0.12.2
```
Comment (boldorider4) [inline recipe/meta.yaml]: you can actually remove `==0.12.2` if it is the only version available.

File: recipe/meta.yaml (hunk 8 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml:59]: https://github.com/AnacondaRecipes/flaml-feedstock/pull/2#discussion_r1901840408

File: recipe/meta.yaml (hunk 9 above)
Comment (boldorider4) [reply recipe/meta.yaml]: or maybe you could specify it like this `>=0.10.2, <=0.12.2`, so you you don't deviate from upstream too much.

File: recipe/meta.yaml [hunk 10]
```diff
@@ -1,52 +1,120 @@
...
+    - transformers >=4.26,<5
+    # Notebook
+    # Duplicated in the test section, comment this line to avoid compilation error.
+    #- openml ==0.10.2,<0.13
+    # Openai
+    - openai >=0.27.4,<0.30
+    # Ray
+    - ray >=1.13,<2.dev0
+    # Spark
+    - pyspark >=3.2.0
```
Comment (boldorider4) [inline recipe/meta.yaml:73]: I would remove the duplicated requirements. If you want to organize them based on which package requires them I would, I would at least comment out the duplicated lines.

File: recipe/meta.yaml [hunk 11]
```diff
@@ -1,52 +1,120 @@
...
+    - joblibspark >=0.5.0
+    # Synapse
+    - joblibspark >=0.5.0
+    - optuna >=2.8.0,<3
```
Comment (boldorider4) [inline recipe/meta.yaml:73]:
```suggestion
    - optuna ==2.8.0
```

File: recipe/meta.yaml [hunk 12]
```diff
@@ -1,52 +1,120 @@
...
+    - pytorch-forecasting >=0.9.0
+    # Hf
+    - transformers >=4.26,<5
+    # Nlp
+    - transformers >=4.26,<5
+    # Notebook
+    # Duplicated in the test section, comment this line to avoid compilation error.
+    #- openml ==0.10.2,<0.13
+    # Openai
+    - openai >=0.27.4,<0.30
```
Comment (boldorider4) [inline recipe/meta.yaml:65]:
```suggestion
    - openai ==0.27.4
```

File: recipe/meta.yaml (hunk 11 above)
Comment (boldorider4) [inline recipe/meta.yaml]:
```suggestion
    - optuna >=2.8.0,<2.9.0
```
I would try to be consistent with the relaxation on `openai`
```
- openai >=0.27.4,<0.30
```

File: recipe/meta.yaml [hunk 13]
```diff
@@ -1,52 +1,120 @@
...
+    # Forecast
+    - holidays <0.14
+    - prophet >=1.0.1
+    - statsmodels >=0.12.2
+    - hcrystalball >=0.1.10,<0.2
+    - pytorch-forecasting >=0.9.0
+    # Hf
+    - transformers >=4.26,<5
+    # Nlp
+    - transformers >=4.26,<5
```
Comment (boldorider4) [inline recipe/meta.yaml]: mind you, it's `transformers[torch]==4.26` so we have to go look into `transformers` for the optional requirements it asks for with the `torch` selector.
https://github.com/huggingface/transformers/blob/820c46a707ddd033975bc3b0549eea200e64c7da/setup.py#L169

File: recipe/meta.yaml (hunk 6 above)
Comment (boldorider4) [reply recipe/meta.yaml:71]: the requirement is this one
https://github.com/ray-project/ray/blob/e4ce38d001dbbe09cd21c497fedd03d692b2be3e/python/setup.py#L220

File: recipe/meta.yaml (hunk 13 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml]: done

File: recipe/meta.yaml (hunk 11 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml]: done

File: recipe/meta.yaml (hunk 10 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml:73]: done

File: recipe/meta.yaml (hunk 9 above)
Comment (Andrii-Osipov) [reply recipe/meta.yaml]: done

**Review by boldorider4 — APPROVED** [review]
